services:
  - type: web
    name: gzarruk_site
    env: python
    buildCommand: "./deploy/build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 gzarruk_site.wsgi:application"
    region: oregon
    plan: free
    numInstances: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: NODE_VERSION
        value: 22.12.0
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: gzarruk_site.settings_production
      - key: DJANGO_DATABASE_NAME
        fromDatabase:
          name: gzarruk_site
          property: database
      - key: DJANGO_DATABASE_USER
        fromDatabase:
          name: gzarruk_site
          property: user
      - key: DJANGO_DATABASE_PASSWORD
        fromDatabase:
          name: gzarruk_site
          property: password
      - key: DJANGO_DATABASE_HOST
        fromDatabase:
          name: gzarruk_site
          property: host
      - key: DJANGO_DATABASE_PORT
        fromDatabase:
          name: gzarruk_site
          property: port
      - key: REDIS_HOST
        fromService:
          type: redis
          name: gzarruk_site-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: gzarruk_site-redis
          property: port
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_ANALYTICS_ID
        sync: false
      - key: SENTRY_DSN
        sync: false
# Celery task worker and scheduler (not available on 'free' plan)
#  - type: worker
#    name: gzarruk_site_celery
#    env: python
#    buildCommand: "./deploy/build_celery.sh"
#    startCommand: celery -A gzarruk_site worker -l INFO --pool gevent --concurrency 20
#    region: oregon
#    plan: starter
#    numInstances: 1
#    envVars:
#      - key: PYTHON_VERSION
#        value: 3.12.8
#      - key: NODE_VERSION
#        value: 22.12.0
#      - key: DEBUG
#        value: false
#      - key: DJANGO_SETTINGS_MODULE
#        value: gzarruk_site.settings_production
#      - key: DJANGO_DATABASE_NAME
#        fromDatabase:
#          name: gzarruk_site
#          property: database
#      - key: DJANGO_DATABASE_USER
#        fromDatabase:
#          name: gzarruk_site
#          property: user
#      - key: DJANGO_DATABASE_PASSWORD
#        fromDatabase:
#          name: gzarruk_site
#          property: password
#      - key: DJANGO_DATABASE_HOST
#        fromDatabase:
#          name: gzarruk_site
#          property: host
#      - key: DJANGO_DATABASE_PORT
#        fromDatabase:
#          name: gzarruk_site
#          property: port
#      - key: REDIS_HOST
#        fromService:
#          type: redis
#          name: gzarruk_site-redis
#          property: host
#      - key: REDIS_PORT
#        fromService:
#          type: redis
#          name: gzarruk_site-redis
#          property: port
#      - key: SECRET_KEY
#        sync: false
#      - key: GOOGLE_ANALYTICS_ID
#        sync: false
#      - key: SENTRY_DSN
#        sync: false
#  - type: worker
#    name: gzarruk_site_celery_beat
#    env: python
#    buildCommand: "./deploy/build_celery.sh"
#    startCommand: celery -A gzarruk_site beat -l INFO
#    region: oregon
#    plan: starter
#    numInstances: 1
#    envVars:
#      - key: PYTHON_VERSION
#        value: 3.12.8
#      - key: NODE_VERSION
#        value: 22.12.0
#      - key: DEBUG
#        value: false
#      - key: DJANGO_SETTINGS_MODULE
#        value: gzarruk_site.settings_production
#      - key: DJANGO_DATABASE_NAME
#        fromDatabase:
#          name: gzarruk_site
#          property: database
#      - key: DJANGO_DATABASE_USER
#        fromDatabase:
#          name: gzarruk_site
#          property: user
#      - key: DJANGO_DATABASE_PASSWORD
#        fromDatabase:
#          name: gzarruk_site
#          property: password
#      - key: DJANGO_DATABASE_HOST
#        fromDatabase:
#          name: gzarruk_site
#          property: host
#      - key: DJANGO_DATABASE_PORT
#        fromDatabase:
#          name: gzarruk_site
#          property: port
#      - key: REDIS_HOST
#        fromService:
#          type: redis
#          name: gzarruk_site-redis
#          property: host
#      - key: REDIS_PORT
#        fromService:
#          type: redis
#          name: gzarruk_site-redis
#          property: port
#      - key: SECRET_KEY
#        sync: false
#      - key: GOOGLE_ANALYTICS_ID
#        sync: false
#      - key: SENTRY_DSN
#        sync: false

# Redis instance (for celery and/or caching)
  - type: redis
    name: gzarruk_site-redis
    region: oregon
    ipAllowList: []
    plan: free

# Postgres database
databases:
  - name: gzarruk_site
    plan: free
    region: oregon
    databaseName: gzarruk_site
    user: gzarruk_site
    ipAllowList: [] # only allow internal connections
